---
- name: Set up ec2 instance for Flaskapp
  hosts: terraform_ubuntu
  remote_user: ubuntu
  become_method: sudo
  become: yes
  
  tasks:
  - name: Connectivity test to EC2 instance
    ansible.builtin.ping:
      data: ping 

  - name: Install dependencies for pip3
    apt:
      update_cache: yes
      name: "{{ item }}"
    with_items:
      - python3-distutils
      - python3-dev
      - python3-setuptools
      - python3-wheel
    become: yes
      
  - name: Install pip3
    apt:
      update_cache: yes
      name: python3-pip
    become: yes

  - name: Install python docker sdk
    shell: |
      pip3 install docker
    become: yes

  - name: Install docker
    apt:
      name: docker.io
    become: yes

  - name: Start Docker
    shell: |
      systemctl start docker
      systemctl enable docker
    become: yes

  - name: Add remote user to docker group
    user:
      name: "ubuntu"
      group: "docker"
    append: yes

  - name: Run image
    shell: docker run --name flaskapp_jenkins -p 5000:5000 -d pavlotarnovetskyi/flaskapp_jenkins
    become: yes