---
- name: Set up ec2 instance for Flaskapp
  hosts: terraform_ubuntu
  remote_user: ubuntu
  become_method: sudo
  become: yes
  
  tasks:
  - name: Connectivity test to EC2 instance
    ansible.builtin.ping:
      data: ping 

  - name: Install docker and run flaskapp.
    shell: |
      sudo apt update
      sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
      sudo apt update
      sudo apt-get install docker-ce -y
      sudo systemctl start docker
      sudo systemctl enable docker
      sudo groupadd docker
      sudo usermod -aG docker ubuntu
      sudo docker pull pavlotarnovetskyi/flaskapp_jenkins
      sudo docker run --name flaskapp_jenkins -p 5000:5000 -d pavlotarnovetskyi/flaskapp_jenkins
    become: yes